import { Alert, FlatList, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

const planLabel: Record<string, string> = { monthly: "شهري", seasonal: "موسمي", yearly: "سنوي" };
const verdictLabel: Record<string, string> = { likely_valid: "يبدو سليماً آلياً", needs_review: "مراجعة يدوية ضرورية", likely_forged: "اشتباه بتلاعب" };
export default function AdminSubscriptionsScreen() {
  const colors = useColors();
  const router = useRouter();
  const { isAuthenticated } = useAuth();
  const query = trpc.subscriptions.adminList.useQuery(undefined, { enabled: isAuthenticated });
  const review = trpc.subscriptions.adminReview.useMutation({ onSuccess: () => query.refetch() });
  const act = (id: number, status: "approved" | "rejected") => { const title = status === "approved" ? "تفعيل الاشتراك" : "رفض الوصل"; Alert.alert(title, status === "approved" ? "تأكدت من الحساب والمبلغ والوصل خارجياً؟ سيتم تفعيل الحساب فوراً." : "هل تريد رفض هذا الوصل؟", [{ text: "إلغاء", style: "cancel" }, { text: status === "approved" ? "تفعيل" : "رفض", style: status === "approved" ? "default" : "destructive", onPress: () => review.mutate({ id, status }) }]); };
  if (!isAuthenticated || query.isError) return <ScreenContainer className="px-5"><View style={styles.denied}><IconSymbol name="lock.fill" size={28} color={colors.primary} /><Text style={[styles.deniedTitle, { color: colors.foreground }]}>صفحة الإدارة</Text><Text style={[styles.deniedText, { color: colors.muted }]}>هذه الشاشة مخصصة لمراجعة وصول الاشتراكات من حساب إداري.</Text></View></ScreenContainer>;
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="arrow.left" size={20} color={colors.foreground} /></Pressable><View><Text style={[styles.title, { color: colors.foreground }]}>مراجعة الاشتراكات</Text><Text style={[styles.subtitle, { color: colors.muted }]}>لا تعتمد على الفحص الآلي وحده</Text></View></View><FlatList data={query.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={[styles.empty, { color: colors.muted }]}>لا توجد وصول قيد المراجعة.</Text>} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><Text style={[styles.status, { color: item.status === "pending" ? colors.warning : item.status === "approved" ? colors.success : colors.error }]}>{item.status === "pending" ? "قيد المراجعة" : item.status === "approved" ? "مقبول" : "مرفوض"}</Text><Text style={[styles.plan, { color: colors.foreground }]}>{planLabel[item.plan]} · {item.amount.toLocaleString("ar-DZ")} دج</Text></View><Text style={[styles.meta, { color: colors.muted }]}>معرّف المستخدم: {item.userId} · {new Date(item.createdAt).toLocaleString("ar-DZ")}</Text><View style={[styles.aiBox, { backgroundColor: item.aiVerdict === "likely_forged" ? "#FDECEC" : "#FFF6DE" }]}><IconSymbol name="sparkles" size={17} color={item.aiVerdict === "likely_forged" ? colors.error : colors.warning} /><Text style={[styles.aiText, { color: colors.foreground }]}>{verdictLabel[item.aiVerdict]} · ثقة {item.aiConfidence}%{"\n"}{item.aiNotes || "لا توجد ملاحظات."}</Text></View><Pressable onPress={() => Linking.openURL(item.receiptUrl)} style={[styles.receipt, { borderColor: colors.primary }]}><IconSymbol name="doc.text.fill" size={16} color={colors.primary} /><Text style={[styles.receiptText, { color: colors.primary }]}>فتح الوصل للتحقق اليدوي</Text></Pressable>{item.status === "pending" && <View style={styles.actions}><Pressable onPress={() => act(item.id, "rejected")} style={[styles.action, { borderColor: colors.border }]}><Text style={{ color: colors.error, fontWeight: "800", fontSize: 12 }}>رفض</Text></Pressable><Pressable onPress={() => act(item.id, "approved")} style={[styles.action, { borderColor: colors.primary, backgroundColor: colors.primary }]}><Text style={{ color: "#FFFFFF", fontWeight: "800", fontSize: 12 }}>موافقة وتفعيل</Text></Pressable></View>}</View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ denied: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, padding: 25 }, deniedTitle: { fontSize: 19, fontWeight: "800" }, deniedText: { fontSize: 12, textAlign: "center", lineHeight: 19 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 13, marginTop: 10 }, back: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" }, title: { fontSize: 24, fontWeight: "800", textAlign: "right" }, subtitle: { fontSize: 11, textAlign: "right", marginTop: 4 }, list: { gap: 12, paddingTop: 22, paddingBottom: 30 }, empty: { textAlign: "center", marginTop: 60, fontSize: 13 }, card: { borderWidth: 1, borderRadius: 17, padding: 15, gap: 10 }, cardTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, plan: { fontSize: 14, fontWeight: "800" }, status: { fontSize: 11, fontWeight: "800" }, meta: { fontSize: 10, textAlign: "right" }, aiBox: { borderRadius: 12, padding: 11, flexDirection: "row-reverse", alignItems: "flex-start", gap: 8 }, aiText: { flex: 1, fontSize: 11, lineHeight: 18, textAlign: "right" }, receipt: { height: 37, borderRadius: 10, borderWidth: 1, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 7 }, receiptText: { fontSize: 11, fontWeight: "800" }, actions: { flexDirection: "row-reverse", gap: 8 }, action: { flex: 1, height: 40, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" },
});
