import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

const demoJobs = [{ id: "demo-1", title: "إصلاح تسرب مياه", customer: "عميل جديد", date: "اليوم، 16:30", status: "pending" }, { id: "demo-2", title: "تركيب مكيف هواء", customer: "عميل متكرر", date: "غداً، 10:00", status: "confirmed" }];
const labels: Record<string, string> = { pending: "طلب جديد", confirmed: "مجدول", completed: "مكتمل", cancelled: "ملغى" };

export default function DashboardScreen() {
  const colors = useColors();
  const router = useRouter();
  const { isAuthenticated } = useAuth();
  const [filter, setFilter] = useState("الكل");
  const query = trpc.dashboard.requests.useQuery(undefined, { enabled: isAuthenticated });
  const update = trpc.dashboard.updateStatus.useMutation({ onSuccess: () => query.refetch() });
  const rows = useMemo(() => !isAuthenticated || !query.data?.length ? demoJobs : query.data.map((item) => ({ id: String(item.id), title: item.subcategory || item.category, customer: "عميل خدمني", date: item.scheduledAt ? new Date(item.scheduledAt).toLocaleDateString("ar-DZ") : "موعد غير محدد", status: item.status })), [isAuthenticated, query.data]);
  const visible = rows.filter((item) => filter === "الكل" || item.status === filter);
  const changeStatus = (id: string, status: "confirmed" | "completed" | "cancelled") => { if (id.startsWith("demo")) { Alert.alert("لوحة الحرفي", "سجّل الدخول وأنشئ ملف الحرفي لإدارة الطلبات الحقيقية."); return; } update.mutate({ id: Number(id), status }); };
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="arrow.left" size={20} color={colors.foreground} /></Pressable><View><Text style={[styles.title, { color: colors.foreground }]}>لوحة الحرفي</Text><Text style={[styles.subtitle, { color: colors.muted }]}>إدارة طلباتك ومواعيدك</Text></View></View>
    <View style={[styles.summary, { backgroundColor: colors.primary }]}><View style={styles.summaryItem}><Text style={styles.summaryValue}>{rows.filter((item) => item.status === "pending").length}</Text><Text style={styles.summaryLabel}>طلبات جديدة</Text></View><View style={styles.summaryDivider} /><View style={styles.summaryItem}><Text style={styles.summaryValue}>{rows.filter((item) => item.status === "confirmed").length}</Text><Text style={styles.summaryLabel}>مواعيد قادمة</Text></View><View style={styles.summaryDivider} /><View style={styles.summaryItem}><Text style={styles.summaryValue}>{rows.filter((item) => item.status === "completed").length}</Text><Text style={styles.summaryLabel}>خدمات مكتملة</Text></View></View>
    <View style={styles.filters}>{[["الكل", "الكل"], ["pending", "جديدة"], ["confirmed", "مجدولة"], ["completed", "مكتملة"]].map(([value, label]) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, { backgroundColor: filter === value ? colors.primary : colors.surface, borderColor: filter === value ? colors.primary : colors.border }]}><Text style={{ color: filter === value ? "#FFFFFF" : colors.muted, fontSize: 11, fontWeight: "800" }}>{label}</Text></Pressable>)}</View>
    <FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><View style={[styles.status, { backgroundColor: item.status === "pending" ? "#FFF3D8" : `${colors.primary}14` }]}><Text style={{ color: item.status === "pending" ? colors.warning : colors.primary, fontSize: 11, fontWeight: "800" }}>{labels[item.status]}</Text></View><View style={[styles.icon, { backgroundColor: `${colors.primary}14` }]}><IconSymbol name="calendar" size={21} color={colors.primary} /></View></View><Text style={[styles.jobTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.meta, { color: colors.muted }]}>{item.customer} · {item.date}</Text>{item.status === "pending" && <View style={styles.actions}><Pressable onPress={() => changeStatus(item.id, "cancelled")} style={[styles.action, { borderColor: colors.border }]}><Text style={{ color: colors.muted, fontSize: 11, fontWeight: "800" }}>رفض</Text></Pressable><Pressable onPress={() => changeStatus(item.id, "confirmed")} style={[styles.action, { backgroundColor: colors.primary, borderColor: colors.primary }]}><Text style={{ color: "#FFFFFF", fontSize: 11, fontWeight: "800" }}>قبول الطلب</Text></Pressable></View>}{item.status === "confirmed" && <Pressable onPress={() => changeStatus(item.id, "completed")} style={[styles.complete, { backgroundColor: `${colors.primary}12` }]}><Text style={[styles.completeText, { color: colors.primary }]}>تحديد كمكتمل</Text></Pressable>}</View>} />
  </ScreenContainer>;
}

const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", alignItems: "center", gap: 13, marginTop: 10 }, back: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" }, title: { fontSize: 27, fontWeight: "800", textAlign: "right" }, subtitle: { fontSize: 12, textAlign: "right", marginTop: 4 }, summary: { borderRadius: 20, padding: 17, flexDirection: "row-reverse", justifyContent: "space-around", alignItems: "center", marginTop: 21 }, summaryItem: { alignItems: "center", gap: 5 }, summaryValue: { color: "#FFFFFF", fontSize: 22, fontWeight: "900" }, summaryLabel: { color: "#D8F7F1", fontSize: 10, fontWeight: "700" }, summaryDivider: { width: 1, height: 34, backgroundColor: "#FFFFFF55" }, filters: { flexDirection: "row-reverse", gap: 7, marginTop: 20 }, filter: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9 }, list: { gap: 11, paddingTop: 14, paddingBottom: 30 }, card: { borderRadius: 18, borderWidth: 1, padding: 15, gap: 9 }, cardTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, icon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, status: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 9 }, jobTitle: { fontSize: 16, fontWeight: "800", textAlign: "right", marginTop: 5 }, meta: { fontSize: 11, textAlign: "right" }, actions: { flexDirection: "row-reverse", gap: 8, marginTop: 6 }, action: { flex: 1, height: 38, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" }, complete: { height: 37, borderRadius: 10, alignItems: "center", justifyContent: "center", marginTop: 4 }, completeText: { fontSize: 11, fontWeight: "800" },
});
